<?php

/** @var \MageSuite\Opengraph\Block\Adminhtml\Preview $block */
/** @var \Magento\Framework\Escaper $escaper */
$tags = $block->getTags();

if ($tags) : ?>
    <div class="admin__fieldset">
        <div class="admin__field">
            <label class="admin__field-label">
                <span><?= /* @noEscape */ __('Preview'); ?></span>
            </label>
            <div class="admin__field-control opengraph_preview">
                <table>
                    <tr>
                        <th><?= /* @noEscape */  __('Property'); ?></th>
                        <th><?= /* @noEscape */ __('Value'); ?></th>
                    </tr>
                    <?php foreach ($tags as $key => $value) : ?>
                        <?php if ($key == 'og:image') {
                            $value = '<img src="' . $escaper->escapeHtmlAttr($value) . '" width="148" />';
                        } elseif ($key == 'og:url') {
                            $preparedUrl = $block->prepareUrl($value);
                            $value = '<a href="' . $escaper->escapeHtmlAttr($preparedUrl) . '">' . $escaper->escapeHtml($preparedUrl) . '</a>';
                        } else {
                            $value = $escaper->escapeHtml(strip_tags($value));
                        } ?>
                        <tr>
                            <td><?= $escaper->escapeHtml($key) ?></td>
                            <td><?= /* @noEscape */ $value ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

    <style>
        .admin__field-control.opengraph_preview table {width: 100%;}
        .admin__field-control.opengraph_preview td, .admin__field-control.opengraph_preview th {border:1px solid #adadad; padding:.6rem 1rem .6rem; text-align: left;}
    </style>
<?php endif; ?>
